### ISSUE TITLE
使用中间件不生效

### ISSUE THREAD

**Issue by admi2u** [liyu001989/dingo-serializer-switch#2]
下载安装后，在 `App\Http\kernel.php` 文件中路由中加入该中间件，并在api路由中设置该中间件，发现返回的数据格式并没有改变，是什么原因呢？
![image](https://user-images.githubusercontent.com/36391186/43300389-8c8f7c8c-9191-11e8-94d2-1a5b3eeb7932.png)

![image](https://user-images.githubusercontent.com/36391186/43300373-79c0915e-9191-11e8-9b0b-c8f97aa3768f.png)

**Comment by liyu001989** [comment]
laravel 5.5 ？并不需要定义在 kernel 中，你把你的环境信息描述一下

**Comment by admi2u** [comment]
@liyu001989 laravel 5.5.40

**Comment by liyu001989** [comment]
代码看着没有问题，检查是不是有路由缓存

https://github.com/summerblue/larabbs   开源项目  api 分支你自己对比一下

**Comment by toknT** [comment]
也不是很熟悉dingo @liyu001989 一开始我也觉得好像没生效 代码这么写的:
```php
return $this->response->collection($messages, new MessageTransformer);
```

但 更具  dingo 的这行 改 resourceKey 
https://github.com/dingo/api/blob/master/src/Transformer/Adapter/Fractal.php#L152
和
fractal 的这行改 serializer 
https://github.com/thephpleague/fractal/blob/master/src/Serializer/ArraySerializer.php#L30
其实应该这么写
```php
        return $this->response->collection($messages, new MessageTransformer, ['key' => 'forbar']);
```
